### ISSUE TITLE
Default image är null

### ISSUE THREAD

**Issue by ecspresso** [SossioG/Syp2-MyHappyPlants#58]
Exception in thread "Thread-5" java.lang.NullPointerException: Cannot invoke "se.myhappyplants.shared.DefaultImage.getThumbnail()" because the return value of "se.myhappyplants.shared.Plant.getDefaultImage()" is null
	at se.myhappyplants.client.view.LibraryPlantPane.<init>(LibraryPlantPane.java:92)
	at se.myhappyplants.client.controller.MyPlantsTabPaneController.addCurrentUserLibraryToHomeScreen(MyPlantsTabPaneController.java:93)
	at se.myhappyplants.client.controller.MyPlantsTabPaneController.lambda$createCurrentUserLibrary$3(MyPlantsTabPaneController.java:141)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ecspresso** [comment]
Detta skulle vara löst i tisdags, koller efter lunch.
